47 adding things to the user entities
CSC207-2022F-UofT/course-project-linkout pull request #49
Opened 2022-11-13 02:47 UTC by czz0120

1. modified class User into abstract class.
2. Made class User a child class of Account.
3. Modified the constructors of three user classes.

2022-11-13 03:01 UTC, Tristal25 submitted a review, later dismissed

2022-11-13 03:40 UTC, alexyin0429 requested changes

2022-11-13 03:40 UTC, alexyin0429 commented on src/main/java/entities/RegUserFactory.java
> +    public User creat(String password, String accountName, Profile profile){
Typo: `public User create(String password, String accountName, Profile profile){`

2022-11-13 03:40 UTC, alexyin0429 commented on src/main/java/entities/Review.java
>      private String comment;
if the comment should not be changed later, then `private final String comment` would be better

2022-11-13 03:40 UTC, alexyin0429 commented on src/main/java/entities/Review.java
>      private int rating;
for rating, same suggestion as below

2022-11-13 03:40 UTC, alexyin0429 commented on src/main/java/entities/User.java
> +    private ArrayList<User> blocked = new ArrayList<>();
`private List<User> blocked = new ArrayList<>();` Sorry, I forgot to change this to List<User>. Could you please modify it for me? Thx

2022-11-13 05:12 UTC, alexyin0429 submitted a review, later dismissed
Looks gooooood to me

2022-11-14 13:58 UTC, ryancys1234 approved these changes
Looks good! I notice that UserFactory has been replaced by RegUserFactory, meaning that every user starts out as a regular user (and may turn into VipUser later on). This is a good decision.

2022-11-14 21:35 UTC, alexyin0429 commented on src/main/java/entities/User.java
> +    }
`countDownRestrictionTime` is added on Nov14. Need to be reviewed. This method is for counting down and updating the restriction time on this user.

2022-11-14 21:36 UTC, alexyin0429 approved these changes

2022-11-14 23:04 UTC, yifeiiZhang approved these changes
good job

2022-11-14 23:29 UTC, clarahqy approved these changes
looks good to me

2022-11-14 23:30 UTC, ryancys1234 approved these changes
Will need to confirm with Alex about countDownTimeRestriction in the User class, but overall okay!

2022-11-14 23:34 UTC, merged